name: Release Rust-Dev Container to GHCR
on:
  workflow_dispatch:
  push:
    tags:
      - "rustdev-v[0-9]+.[0-9]+.[0-9]+"
  
env:
  # For the release action, you'll have to set the following variables
  GITHUB_TOKEN: ${{ secrets.CONTAINERS_GITHUB_TOKEN }}

jobs:
  build_dev_container:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout (GitHub)
      uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ env.GITHUB_TOKEN }}
    - name: Pre-build dev container image
      uses: devcontainers/ci@v0.2
      with:
        subFolder: Rust/Rust-Dev
        imageName: ghcr.io/dev-containers/rust-devcontainer
        cacheFrom: ghcr.io/dev-containers/rust-devcontainer
        push: always
